#pragma once

// =============================================================================
// Game module API
// -----------------------------------------------------------------------------
// A game is a DLL (ex : Blocky.dll) loaded by a host.
//
// A host is an executable of the engine : the editor (src/editor) or the
// runtime (src/runtime) that plays a project without the editor.
//
// Required export (generated by LYNX_LINK_MODULE, see Factory.h) :
//   FactoryRegisterClasses / FactoryUnregisterClasses
//
// Optional exports, looked up by name with SysModule::GetSymbol(). The host
// simply skips a function the game does not export. They are plain C functions
// (extern "C", no C++ types) so the name and the ABI stay stable.
//
// In the game :
//
//     LYNX_GAME_EXPORT void LynxGame_SetupScene(uint32_t scene) { ... }
//
// HRL ids (scene, camera...) are passed as uint32_t (= HRL_id).
// =============================================================================

#include <cstdint>

#ifdef _WIN32
#define LYNX_GAME_EXPORT extern "C" __declspec(dllexport)
#else
#define LYNX_GAME_EXPORT extern "C" __attribute__((visibility("default")))
#endif

namespace lynx::game_api
{
	// Called once the scene exists, its voxel world is loaded and the voxel
	// types (assets/voxels.json) are applied, before the level is created ;
	// and again after every reload of the game DLL.
	// The game registers its voxel events here (lynx::voxels).
	using SetupSceneFn = void (*)(uint32_t scene);
	constexpr const char* kSetupScene = "LynxGame_SetupScene";

	// The game starts / stops : runtime start and exit, editor Play / Stop.
	// (music, game-wide state...)
	using OnGameStartFn = void (*)();
	constexpr const char* kOnGameStart = "LynxGame_OnGameStart";

	using OnGameEndFn = void (*)();
	constexpr const char* kOnGameEnd = "LynxGame_OnGameEnd";

	// Called every time a level was (re)created : startup, game DLL reload,
	// editor "Stop". Lets the game snap its gameplay camera, cache ids...
	using OnLevelLoadedFn = void (*)(uint32_t gameplay_camera);
	constexpr const char* kOnLevelLoaded = "LynxGame_OnLevelLoaded";

	// Called every frame, after the engine tick. The game moves its gameplay
	// camera (follow the player, camera shake...).
	using UpdateGameplayCameraFn = void (*)(uint32_t gameplay_camera, float dt);
	constexpr const char* kUpdateGameplayCamera = "LynxGame_UpdateGameplayCamera";

	// Collision debug overlay (editor F4). 0 = off, 1 = on.
	using SetCollisionDebugEnabledFn = void (*)(int enabled);
	constexpr const char* kSetCollisionDebugEnabled = "LynxGame_SetCollisionDebugEnabled";


	// Host side : every optional function of the loaded game DLL.
	// A nullptr member means "not exported by this game".
	struct Hooks
	{
		SetupSceneFn setup_scene = nullptr;
		OnGameStartFn on_game_start = nullptr;
		OnGameEndFn on_game_end = nullptr;
		OnLevelLoadedFn on_level_loaded = nullptr;
		UpdateGameplayCameraFn update_gameplay_camera = nullptr;
		SetCollisionDebugEnabledFn set_collision_debug_enabled = nullptr;

		// ModuleT = lynx::SysModule (anything with void* GetSymbol(const char*)).
		template <class ModuleT>
		void Load(const ModuleT& module)
		{
			setup_scene = reinterpret_cast<SetupSceneFn>(module.GetSymbol(kSetupScene));
			on_game_start = reinterpret_cast<OnGameStartFn>(module.GetSymbol(kOnGameStart));
			on_game_end = reinterpret_cast<OnGameEndFn>(module.GetSymbol(kOnGameEnd));
			on_level_loaded = reinterpret_cast<OnLevelLoadedFn>(module.GetSymbol(kOnLevelLoaded));
			update_gameplay_camera = reinterpret_cast<UpdateGameplayCameraFn>(module.GetSymbol(kUpdateGameplayCamera));
			set_collision_debug_enabled = reinterpret_cast<SetCollisionDebugEnabledFn>(module.GetSymbol(kSetCollisionDebugEnabled));
		}

		// To call BEFORE the DLL is unloaded : the pointers would dangle.
		void Clear()
		{
			*this = Hooks{};
		}
	};
}
