#pragma once

#include "core/Engine.h"
#include "core/Level.h"
#include "core/Common.h"
#include "core/Filesystem.h"
#include "core/Factory.h"
#include "core/Localization.h"
#include "core/RessourceManager.h"
#include "core/Utils.h"
#include "core/Voxels.h"
#include "core/Profiler.h"

#include "core/data/DataEnum.h"
#include "core/data/EventDispatcher.h"
#include "core/data/IniParser.h"
#include "core/data/Observable.h"
#include "core/data/OrderedMap.h"
#include "core/data/Typename.h"

#include "gameplay/Object.h"
#include "gameplay/Actor.h"
#include "gameplay/Component.h"
#include "gameplay/Components.h"
#include "gameplay/SpriteComponents.h"
#include "gameplay/CameraComponent.h"
#include "gameplay/PlayerController.h"
#include "gameplay/BoxColliderComponent.h"
#include "gameplay/SoundSourceComponent.h"
#include "gameplay/LightComponent.h"
#include "gameplay/EngineActors.h"
#include "gameplay/Input.h"
#include "gameplay/CameraShake.h"
#include "gameplay/AnimationSystem.h"

#include "scripting/Scripting.h"

#include "audio/AudioSource.h"
#include "audio/AudioListener.h"
#include "audio/Audio2D.h"

#include "widgets/Widget.h"
#include "widgets/Panels.h"
#include "widgets/CommonWidgets.h"
#include "widgets/UserWidget.h"